//! Object system
//!
//! Contains object classes (templates) and instances.

mod container;
pub mod inventory;
mod mkobj;
mod obj;
mod objclass;
mod objname;

pub use container::{
    ContainerResult,
    TrapType,
    can_put_in_container,
    // Container UI functions
    ck_bag,
    container_weight,
    count_contents,
    count_total_items,
    empty_container,
    find_by_id,
    find_in_container,
    force_container,
    in_container,
    is_container_in_use,
    list_contents,
    lock_container,
    open_container,
    put_in_container,
    take_from_container,
    take_quantity_from_container,
    tipcontainer,
    total_weight,
    unlock_container,
    use_container,
    validate_container,
};
pub use inventory::{
    // Core inventory functions
    assign_invlet,
    calc_capacity,
    carrying_blessed,
    carrying_cursed,
    carrying_lit,
    // Query functions
    count_buc,
    count_obj,
    count_unpaid,
    ddoinv,
    // Display/UI functions
    display_inventory,
    display_packed_inventory,
    doprarm,
    doprwep,
    dotypeinv,
    encumbrance_name,
    find_by_letter,
    // Weight/capacity
    inv_weight,
    is_full,
    item_count,
    slot_count,
    weight_cap_bonus,
};
pub use mkobj::{
    CORPSE,
    ClassBases,
    CorpstatFlags,
    EGG,
    FIGURINE,
    LocationType,
    MkObjContext,
    PM_LICHEN,
    PM_LIZARD,
    STATUE,
    bless,
    bless_or_curse,
    buc_sign,
    can_merge,
    corpse_is_rotten,
    corpse_is_tainted,
    curse,
    merge_obj,
    mkcorpse,
    // Corpse creation
    mkcorpstat,
    mkgold,
    mkobj,
    mkobj_random,
    mkobj_random_with_data,
    mkobj_with_data,
    mksobj,
    mksobj_with_data,
    select_object_type,
    set_corpsenm,
    split_obj,
    start_corpse_timeout,
    unbless,
    uncurse,
};
pub use obj::{
    BucStatus,
    Object,
    ObjectId,
    ObjectLocation,
    addtobill,
    attacks,
    // Phase 5: Light Sources
    begin_burn,
    // Bypass functions
    bypass_obj,
    bypass_objlist,
    can_be_billed,
    candle_sheds_light,
    clear_bypasses,
    costly_spot,
    curr_cnt,
    cursed,
    cursed_object_at,
    cursetxt,
    discover_object,
    dropx,
    dropy,
    end_burn,
    erode_obj,
    extract_nexthere,
    // Pile/chain functions
    extract_nobj,
    find_oid,
    flooreffects,
    g_at,
    get_obj_weight_single,
    grease_protect,
    hold_another_object,
    is_adjacent,
    is_corrodeable,
    is_damageable,
    // Phase 6: Materials & Erosion
    is_flammable,
    is_rottable,
    is_rustprone,
    is_visible_from,
    // Object movement
    lift_object,
    light_emitting_objs,
    light_radius,
    makeknown,
    merge_choice,
    nexthere,
    nxtobj,
    o_material,
    obj_adjust_light_radius,
    // Lifecycle functions
    obj_extract_self,
    obj_falls_off_hero,
    obj_here,
    obj_is_destroyed,
    obj_is_in_use,
    obj_is_piletop_at,
    // Object property functions
    obj_is_pname,
    obj_material_is_flammable,
    obj_material_is_rustprone,
    obj_name_from_material,
    // Phase 7: Polish & Edge Cases
    obj_no_longer_held,
    obj_nutrition,
    obj_reflects,
    obj_resists,
    obj_resists_damage,
    obj_scatter,
    obj_sheds_light,
    obj_sheds_light_anywhere,
    obj_sheds_light_radius,
    // Phase 5: Shop Integration
    obj_value,
    objects_are_same_material,
    pay_bill,
    // Placement functions
    place_object,
    protects,
    remap_obj_material,
    remove_object,
    retouch_equipment,
    retouch_object,
    rndcurse,
    rust_dmg,
    select_hwep,
    select_off,
    set_bknown,
    shk_move,
    snuff_candles,
    sobj_at,
    splittable,
    stackobj,
    subfrombill,
    torch_sheds_light,
    // Weight functions
    weight,
};
pub use objclass::{
    ArmorCategory,
    DirectionType,
    DiscoveredType,
    DiscoveryState,
    Material,
    ObjClassDef,
    ObjectClass,
    // Object class helper functions
    def_char_to_objclass,
    interesting_to_discover,
    kind_name,
    let_to_name,
    obj_to_let,
    objtyp_is_callable,
    oc_to_str,
    oclass_to_name,
};
pub use objname::{
    An,
    ObjectKnowledge,
    The,
    Yname2,
    Ysimple_name2,
    an,
    // Capitalized versions
    an_capitalized,
    base_object_name,
    // Corpse/special object naming
    corpse_xname,
    distant_name,
    // Advanced naming functions
    doname,
    egg_xname,
    figurine_xname,
    full_object_name,
    killer_corpse_xname,
    killer_xname,
    makeplural,
    makesingular,
    obj_typename_from_obj,
    quantity_name,
    readobjnam,
    simple_object_name,
    simple_typename,
    singular,
    statue_xname,
    the,
    the_capitalized,
    xname,
    yname,
    ysimple_name,
};
